/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2ef30d59ac1cf2e87eb757e03a73c12d)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	RL_INQUIRY: RateLimit;
	RL_LOGIN: RateLimit;
	RL_ORDER: RateLimit;
	PUBLIC_SITE_URL: "https://my-website.sarisi1705.workers.dev";
	TELEGRAM_BOT_TOKEN: string;
	TELEGRAM_CHAT_ID: string;
	TURNSTILE_SECRET_KEY: string;
	IP_HASH_SALT: string;
	TELEGRAM_WEBHOOK_SECRET: string;
	TURNSTILE_SITE_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_SITE_URL" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_CHAT_ID" | "TURNSTILE_SECRET_KEY" | "IP_HASH_SALT" | "TELEGRAM_WEBHOOK_SECRET" | "TURNSTILE_SITE_KEY">> {}
}
